var bohaterowie_male = [
"Aquaman",
"Batman",
"Shazam",
"Anarky",
"Arrow",
"Etrigan",
"Atom",
"Azrael",
"Bat-Mite",
"Beast boy",
"Kapitan Carrot",
"Blue Beetle",
"Doktor Fate",
"Robin",
"Nightwing",
"Red Hood",
"Hawkman",
"Constantine",
"Superman",
"Green Lantern"
];

var bohaterowie_female = [
"BatGirl",
"Catwoman",
"Carol Ferris",
"Wonder Woman",
"Wonder Girl",
"Zatanna",
"Star Fire",
"Mera",
"Shiva",
"Gabriele Doe",
"Martha Wayne",
"Alexandra Luthor",
"Hawk Girl",
"Cassandra Kain",
"Angela Roth",
"Talia al Ghul",
"Reven"
];

var evilman = [
"Darkseid",
"Merlin",
"ScareCrow",
"DoomsDay",
"Joker",
"Bane",
"Sinestro",
"Ichabod",
"Killer Croc",
"Deathstroke",
"Hugo Strange",
"FireFly",
"Harley Queen",
"Trigon",
"Lex Luthor",
"War",
"Braniac",
"Janusz Tracz",
"Batman who laughs",
"Harley Dent",
"Peugwin",
"Doomsday Batman"
];

var aktorzy_male = [
"Mikołaj Roznerski",
"Wojciech Cejrowski",
"Korwin",
"Bercik",
"Marcin Daniec",
"Abelard Giza",
"Robert Górski",
"Cezary Pazura",
"ten menel spod sklepu",
"proboszcz",
"papież",
"Artur Andrus",
"Eugeniusz Bono",
"Tadeusz Drozda",
"Krzysztof Czeczot",
"Paweł Domagała",
"Łukasz Garlicki",
"Jan Frycz",
"Tomasz Kot",
"Piotr Adamczyk",
"Wojciech Mecwaldowski",
"Tomasz Karolak",
"Maciej Stuhr",
"Borys Szyc",
"Zbigniew Zamachowski",
"Rafał Królikowski",
"Michał Koterski",
"Maciej Zakościelny",
"Paweł Małaszyński",
"Rafał Cieszyński",
"Mateusz Damięcki",
"Wojciech Solarz",
"Jakub Wesołowski",
"Rafał Rutkowski",
"Piotr Głowacki",
"Dariusz Kowalski",
"Paźdioch",
"Ferdek Kiepski",
"Waldemar Kiepski"
];

var aktorzy_female = [
"Weronika Rosati",
"Barbara Kurdej-Szatan",
"Anna Dereszowska",
"Danuta Stenka",
"Anna Mucha",
"Katarzyna Figura",
"Katarzyna Bujakiewicz",
"Sonia Bohosiewicz",
"Małgorzata Kożuchowska",
"Agnieszka Dygant",
"Magdalena Różczka",
"Anna Dereszowska",
"Marta Żmuda Trzebiatowska",
"Edyta Olszówka",
"Małgorzata Socha",
"Katarzyna Zielińska",
"Roma Gąsiorowska",
"Izabela Kuna",
"Olga Bołądź",
"Joanna Bartel",
"Agnieszka Więdłocha"
];

var zawod = [
"zabił swojego wroga ",
"zgubił się w ciemnej nocy",
"zagubił swoją tożsamość",
"opuścił swoje miasto",
"spalił swój strój",
"ma problemy emocjonalne",
"ma problem ze swoją płcią",
"rozbił Bat Sygnał",
"nie może się pogodzić, kim się stał",
"dołączył się do mrocznego kultu cthulhu",
"dołączył się do kultu Latającego Potwora Spaghetti",
"nie uratował Gotham",
"pracuje dla Janusza Tracza",
"stracił posadę w Justice Leauge",
"ma problemy psychiczne",
"pobił rysownika Marvela",
"skończył szkołę marketingu",
"został programistą baz danych",
"skoczył z mostu",
"pracuje w cyrku",
"wywołał między galaktyczny sexskandal",
"słyszy głosy",
"został menelem",
"został coachem",
"zabił przypadkowo policjanta",
"zranił swojego przyjaciela",
"zwątpił w swój cel życiowy",
"znalazł zniszczony strój swojego bohatera z dzieciństwa",
"zniszczył mienie publiczne",
"sprowadził na świat zagładę",
"porzucił swoją przeszłość",
"nie uratował prezydenta",
"poznał szokujący skandal",
"rysuje komiksy o swoich przygodach, jednak dostaje wypowiedzenie z pracy od DC Comics",
"zwątpił w swój cel życiowy",
"zdradził przyjaciół",
"nie panuje nad sobą",
"nie panuje nad swoimi mocami",
"nie panuje nad swoim mrokiem",
"stracił swoje ukochany dom",
"spalił mu się samochód",
"uzależnił się od narkotyków",
"dowiedział się że Ziemia jest płaska",
"powstał z martwych"
];

var no_i_co_z_nia_robil = [
"zastrzelił",
"wyznaje swoje słabości",
"wykorzystał moment słabości",
"próbował ratować związek z ",
"zamordował z zimną krwią ",
"skaleczył",
"zdradził swoją jedyną w najgorszy sposób",
"oszukał",
"opuścił",
"musiał zmusić do potwornej rzeczy ",
"doniósł na ",
"postanawia zerwać kontakt w imie ratowania ludzkości z ",
"odkrył strasznie mroczny sekret ",
"odkrył ohydną tajemnicę"
];





var kto = [
"społeczność Facebooka",
"fani Marvela",
"połowa Gotham",
"pieniądz",
"James Gordon",
"goście odpowiedzialni za DC Universe",
"koleżanka",
"rząd DC",
"premier",
"połowa Śląska",
"jego kostium",
"rząd Ameryki",
"cała Bat-rodzina",
"były Prezydent USA",
"ludkość od IT",
"jej ex-przyjacióła",
"jej ręka",
"Stalin",
"Rasputin",
"Chiński Cesarz",
"Hitler",
"jego teść",
"jego noga",
"jej pies",
"ich Bank",
"ich kot",
"chłopak",
"babcia",
"dziadek",
"chomik",
"Iron Maiden",
"Metallica",
"Modern Talking",
"Elvis Presley",
"ich ulubiony zespół Trash Metalowy",
"brat",
"połowa redakcji Daily Planet",
"cały DC",
"kuzyn",
"ich sąsiad",
"ex"
];

var co_z_kobieta = [
"zrujnowała swoją karierę",
"nie ma pieniędzy",
"próbowała użyć swoich mocy w imię dobra, a sprowadziła śmierć",
"nie pamięta swojej przeszłości",
"postanawia nigdy nie używać swoich mocy",
"okradła biedne dzieci",
"straciła swój dom",
"zepsuła swój samochód",
"prosi o pomoc Xmen",
"skrytkowała polski rząd",
"pozwoliła się zdemaskować",
"ma wątpliwośći co do otaczającej jej rzeczywistości",
"przypadkowo zamordowała agenta FBI",
"odkryła, że jest kosmitą",
"odkryła, że należy do uniwersum Marvela",
"odkryła, że dotychczas łamała prawa fizyki",
"przypomniała swoje zbrodnie z przeszłości",
"odnalazła Adolfa Hitlera",
"spodobało jej się Mein Kauf",
"odkryła spisek, że Ziemia jest płaska",
"umarło w niej dobro",
"straciła nadzieję",
"zachorowała na ciężką chorobę",
"odkryła, że wkrótce umrze",
"jest alkoholiczką",
"przegrała życie",
"zrozumiała, że cokolwiek zrobi, to czyni nieszczęście",
"sprowadza zagładę na świat",
"udowodniła, że Dinozaury zostały stworzone przez USA",
"stwierdziła, że ludzkość została stworzona przez kosmitów",
"jest antyszczepionkowcem",
"przebłagała chłopaka, żeby kupił jej działkę",
"hoduje podejrzane kwiatki",
"nie zdała egzaminu gimnazjalnego",
"zdradziła go z sąsiadem",
"została zwolniona z baru szybkiej obsługi",
"nie zdała matury",
"rozbiła samochód podczas egzaminu na prawo jazdy",
"poznała sekretną tożsamość jej chłopaka na Tinderze",
"stwierdziła, że film Batman vs Superman jest dziełem sztuki",
"zrujonowała swoją karierę",
"rozlała wódkę",
"straciła pracę",
"występuje jako aktorka porno",
"prowadzi burdel",
"zalega z czynszem",
"wypiła za dużo wódki",
"zaczeła kupować komiksy z Marvela"
];

var co_sie_dzieje = [
"zdradza ją z jej najlepszą koleżanką",
"ginie w wyniku eksplozji atomowej",
"zostaje zabita przez potrąconie samochodem",
"ginie w niewyjaśnionych okolicznościach",
"zostaje porwany przez UFO",
"umiera w męczarniach przez nią",
"stwierdza że kłamie",
"przemawia dziwnym głosem",
"zabrali im pieniądze",
"odnalazło 7 jąder atomowych",
"wypowiada krwawą wojnę",
"stało się niewolnikami systemu",
"przestaje się do niej odzywać",
"posiada zdolności paranormalne",
"posiada zdolności magiczne",
"widziała Smoka",
"przedawkowali narkotyki i umierają",
"przechodzi na stronę zła",
"wykupili prenumeratę Daily Planet",
"oskarża ich o zło",
"chce ich zabić",
"dostaje misję uratowania wszechświata",
"zostaje wystrzelony na marsa bez powrotu",
"zostaje wysłany na misję samobójczą",
"znajduje portal prowadzący do uniwersum Marvela",
"nienawidzą ich",
"chcą się zemścić",
"chcą ich zabić",
"domaga się sprawiedliwości",
"czują zagrożenie",
"dzwoni po policję gdy ich widzi",
"gardzą nimi"
];

var co_postanawia = [
"opuścić miasto",
"skończyć ze sobą",
"opuścić planetę",
"umrzeć",
"pozbawić się swoich mocy",
"udać się do psychiatry",
"skoczyć z wieżowca",
"wyjechać za granicę",
"nakłonić DC by sprzedała jej postać do Marvela",
"zostać mnichem tybetańskim",
"nauczyć się tańczyć",
"zniszczyć mafię",
"dołączyć do Amandy Walker",
"dołączyć do Lexa Luthora",
"dołączyć do protestujących",
"zapolować i zabić swoich wrogów",
"wyruszyć na podróż by szukać swojego sensu życia",
"się zemścić",
"znaleźć nową pracę",
"zniszczyć wszechswiat",
"odciąć się od rodziny",
"spędzić noc z jej wrogiem",
"zbudować nową broń",
"znaleźć innego faceta, póki jeszcze może",
"zmienić swoje życie",
"pić wino do samego rana",
"dołączyć się do Darkseida",
"rzucić to wszystko i wyjechać w Bieszczady"
];

var a_co_z_wrogiem = [
"przeciera oczy ze zdziwienia",
"nie wierzy że oni są tak głupi",
"przeprasza za II Wojnę Światową",
"prowadzi program na TVN24",
"stworzył o tym odcinek w programie paradokumentalnym", 
"zgłosił ich sprawę do programu ,,Sprawa dla reportera''",
"prowadzi partię polityczną z programem likwidacji patologii, jaką tworzą nasi bohaterowie",
"trzyma kciuki za ich związek",
"wypuł kawę gdy o tym usłyszał",
"otrzymał zaproszenie na ich ślub",
"prowadzi stronę internetową przeciwko im",
"włamał się na ich konto na facebooku",
"przekonał Netflixa do stworzenia o tym serialu",
"dostał na nich zlecenie",
"puknął się w głowę",
"strzelił sobie w łeb",
"stracił nadzieję na romans",
"szuka żony na Tinderze",
"próbuje sprzedać malucha za pół miliona złotych",
"wie jak z Polski zrobić potęgę ekonomiczną",
"wygrał wybory do Rady Europejskiej",
"chwali się jakim potężnym artefaktem jest paszport Polsatu",
"nakłonił ich kota, by nasrał im na łózko",
"nakłonił ich psa, by dolał trucizny do ich zupy",
"sprzedał im kradzioną złotówkę za 5 zł",
"powiadomił o tym służby",
"podał ich do sądu",
"był jej poprzednim kochankiem",
"napisał hejty na ich kanale youtube",
"został ich lokajem",
"nie wie, że jest ojcem jej przyszego dziecka",
"wstał i zaczął bić im brawo",
"podstawił im pod drzwi stado kotów, coś przy tym sugerując...",
"napisał książkę bestseller o ich życiu",
"zaczął kwestionować w swój sens życia",
"czasami odwiedza ją w nocy"
];

var ale_czy_co = [
"ich związek przetrwa próbę czasu",
"uda się przejść Dooma na pralce",
"Ichabod przestanie pić piwo i zacznie pić coś lepszego, np wódkę",
"Windows 10 przestanie pobierać aktualizację",
"przekonają Warner Bros do przywrócenia oryginalnych Teen Titans",
"ten rok będzie rokiem Linuxa na desktopach",
"przekonają lewaków do prawicowych ideii",
"uda im się wywołać Batmana, gdy użyli symbolu Supermana na zielonej latarnii",
"uda im się odnaleźć Power Rangers",
"uda im się wywołać Kapitana Planetę",
"uda się uratować galaktykę Curwix przed złymi kosmitami",
"uda się przywrócić Kapitana Bombę",
"uda się zakończyć wojnę na Cybertronie",
"uda się przekonać Linuxiarzy do Windowsa",
"uda im się przekonać PC Master Race do konsol",
"stworzą crossovera z Marvelem",
"uda im się wejść do Narnii za pomocą sedesu",
"złapią autobus gdy ten odjeżdża za minutę",
"uda się obliczyć równania różniczkowe, gdy nie znają całek",
"uda się uruchomić natywnie aplikację na Windowsa na Linuxie, gdy nie wiedzą o WINE",
"uratują Disneyland przed Wojną Klonów",
"przekonają Eminema do stworzenia o nich utworu",
"uda się przebłagac kompa z Windows 10 by nie robił tej wielkiej aktualizacji 2 minuty przed obroną inżynierską",
"wygrają turniej 1 z 10",
"udowodnią, że Ziemia jest naleśnikiem, a Mars sernikiem",
"Warszawa obroni się przed hordą zmutowanych zombie",
"wyborcy zagłosują na zmiennokształtnego jaszczura w ciele człowieka",
"uda się przeprowadzić uczciwe wybory, gdy ludzie od opozycji są torturowani przez jaszczuro-ludzi",
"unieważnić ustawę zakazu handlu w niedzielę",
"meteory zniszczą ziemię",
"gołąb pocztowy z obciążeniem 2 kg będzie szybszy od 3 kilogramowej jaskółki afrykańskiej, ktora leci pod wiatr",
"cola będzie zdrowotnym napojem z witaminami",
"udowodnią że syrop glukozo fruktozowy to samo zdrowie",
"uda się babci rozwiązać krzyżówkę",
"inflacja zniszczy majątek Wayne'a",
"uda się udowodnić istnienie UFO",
"czy Robert oderwie się od komputera na te 10 minut",
"typowy Nerd spotka tą swoją jedyną połówkę w Tibii",
"Konstytucja w Polsce będzie przestrzegana",
"uda się oczyścić Wisłę",
"uda się oczyścić powietrze w Krakowie",
"dzięki temu DC Universe zacznie mieć lepsze wyniki finansowe",
"dostaną pieniądze z 500+, gdy mają wyższe zarobki",
"Plastic Man przestanie być takim ciamajdą",
"uda się poprosić Zacka Syndera o zmianę ich żywota",
"uda się przekonać DC do ponownego restartu",
"Polacy dostaną się do Mistrzostw Świata",
"walcząc z demonami nabiją expa",
"uda się wydać trylogię Gothica na nową generację",
"uda się znaleźć konia na białym rycerzu",
"ktoś widział dziub-dziuba?",
"w innym dniu pierogi są tak samo smaczne jak w piątek",
"żyrafy to tak naprawdę przebrane dinozaury",
"zarobią na małego fiata",
"zaczną w Polsce uczciwie pracować",
"uda się zarobić na tym większą kasę",
"unikną poborcy podatkowego",
"Polska dogoni gospodarczo całą Europę",
"Polska przetrwa atomową apokalipsę"
];

function losuj(tablica){
	return tablica[Math.floor(Math.random()*tablica.length)];
}

function odmien(imie){
	if(imie == "Paweł"){
		return "Pawła";
	}else if(imie == "Antoni"){
		return "Antoniego";
	}else if(imie == "Ksawery"){
		return "Ksawerego";
	}else if(imie == "Kacper"){
		return "Kacpra";
	}else if(imie == "Ignacy"){
		return "Ignacego";
	}else if(imie == "Franciszek"){
		return "Franciszka";
	}else{
		return imie + "a";
	}
}

function generuj(){
	var zdanie = losuj(bohaterowie_male) + " (" + losuj(aktorzy_male) + ") " +  losuj(zawod) + " i " + losuj(no_i_co_z_nia_robil) +" "+ losuj(bohaterowie_female) + " (" + losuj(aktorzy_female) + ")" + ", która " + losuj(co_z_kobieta) + ". Niestety, okazuje się, że " + losuj(kto) + " " + losuj(co_sie_dzieje) + ", więc ona postanawia " + losuj(co_postanawia) + ". Tymczasem " + losuj(evilman) + " (" + losuj(aktorzy_male) + ") " + losuj(a_co_z_wrogiem) +". Ale czy " + losuj(ale_czy_co) + "?";
	document.getElementById("gen").innerText = zdanie;
}
